"""added several tables

Revision ID: 525d3f9ef6d8
Revises: 64368dcbffaa
Create Date: 2022-04-13 17:58:24.901908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525d3f9ef6d8'
down_revision = '64368dcbffaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoicesupplierdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chamber_of_commerce_registration_number', sa.String(), nullable=False),
    sa.Column('vat_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('iban', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('leaseagreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_agreement_number', sa.Integer(), nullable=False),
    sa.Column('asset_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('reserved_amount', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoicesgeneral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('vat_value', sa.Float(), nullable=False),
    sa.Column('free_of_vat', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('initial', 'pending', 'waiting_for_apporval', 'approved', 'approved_twice', 'completed', 'paid_out', name='invoicestatus'), server_default='initial', nullable=True),
    sa.Column('step_left_off', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.Column('invoice_supplier_details_id', sa.Integer(), nullable=True),
    sa.Column('lease_agreement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_supplier_details_id'], ['invoicesupplierdetails.id'], ),
    sa.ForeignKeyConstraint(['lease_agreement_id'], ['leaseagreements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoicesgeneral')
    op.drop_table('leaseagreements')
    op.drop_table('invoicesupplierdetails')
    # ### end Alembic commands ###
