"""add invoice status enum

Revision ID: d1afd712d92a
Revises: 525d3f9ef6d8
Create Date: 2022-04-13 18:19:08.946767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = 'd1afd712d92a'
down_revision = '525d3f9ef6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    invoice_status = postgresql.ENUM('initial', 'pending', 'waitingForApproval', 'approved' , 'approved_twice' , 'complated', 'paidOut', name="invoicestatus")
    invoice_status.create(op.get_bind())

    initial = "initial"
    pending = "pending"
    waiting_for_apporval = "waitingForApproval"
    approved = "approved"
    approved_twice = "approved_twice"
    completed = "complated"
    paid_out = "paidOut"
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
